<?php
$nameCount = 1;

// Static names TEMP
$name1 = "Counter Strike : Global Offensive";
?>


<div id="step1">


<table>
<tr>
<td>
<h2>Web Services</h2>
<br>
<div class="list">
<ul class="navlist">
	<a href="#"><li>Web Space Basic</li></a>
	<a href="#"><li>Web Space Silver</li></a>
	<a href="#"><li>Web Space Gold</li></a>
	<a href="#"><li>.co.uk Domain + Setup</li></a>
	<a href="#"><li>Web Design Setup</li></a>
</ul>
</div>
</td>
<td>
<h2>Game Packages</h2>
<br>
<div class="list">
<ul class="navlist">
	<a class="<?php echo str_replace(' ', '_',(strtolower($name) . $nameCount)); $nameCount++;?>" href="#"><li><?php echo $name . $nameCount;?></li></a>
	<a href="#"><li>Minecraft</li></a>
	<a href="#"><li>Garrys Mod</li></a>
	<a href="#"><li>Tekkit</li></a>
	<a href="#"><li>Terraria</li></a>
</ul>
</div>
</td>
</tr>
</table>
<p>If your looking for something that is not here, <a href="mailto:<?php $this->email;?>">email us!<a/></p>
</div>

<div id="step2">

</div>


<div id="step3">
STEP THREE
</div>
