<?php
$this->siteName = "Test";
?>
<head>
    <title><?php echo $this->siteName;?> | Billing</title>

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="public/css/style.css" />
</head>
<body>
<div id="header">
	<div class="left">
	LOGO | LOGIN | LOGOUT | REGISTER | Forgot Password?
	</div>
	
	<div class="right">
		<ul>
        <li>Copyright <?php echo $this->siteName;?> <?php echo date('Y');?></li>
		<li>Copyright <?php echo $this->siteName;?> <?php echo date('Y');?></li>
		<li><em>jbilling</em> by Scott Ramsden</li>
		</ul>
	</div>
</div>
<div id="main">
    main content
</div>
<div id="steps">

    <div class="left leftarrow step"></div>
    <div class="right rightarrow step"></div>

</div>
</body>
