<?php
$this->SiteName = "Test";
?>
<head>
    <title><?php echo $this->siteName;?> | Billing</title>

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="public/css/style.css" />
</head>
<body>

<h2>Welcome to <?php echo $this->siteName;?></h2>

    <ul>
        <!-- Loop to catch all options -->
        <li>Im Looking to <?php echo $options;?></li>

    </ul>


<div id="footer">
    <ul>
        <li>Copyright <?php echo $this->siteName;?> <?php echo date('Y');?></li> | <li>Copyright <?php echo $this->siteName;?> <?php echo date('Y');?></li> | <li>jbilling</li>
    </ul>
</div>

</body>
